apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: restorejob-deleter
rules:
- apiGroups: [""]
  resources: ["restorejobs"]
  verbs: ["get", "delete", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: RoleBinding
metadata:
  name: restorejob-deleter
  namespace: wordpress
subjects:
# You can specify more than one "subject"
- apiGroup: ""
  kind: ServiceAccount
  name: default
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole #this must be Role or ClusterRole
  name: restorejob-deleter # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
---

