apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: restorejob-role
rules:
- apiGroups: ["hostkraken.com"]
  resources: ["restorejobs"]
  verbs: ["get", "delete", "list"]
- apiGroups: ["batch","extensions"]
  resources: ["jobs"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: ClusterRoleBinding
metadata:
  name: restorejob-binding
subjects:
# You can specify more than one "subject"
- apiGroup: ""
  kind: ServiceAccount
  name: default
  namespace: wordpress
roleRef:
  kind: ClusterRole #this must be Role or ClusterRole
  name: restorejob-role # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
---

